### ISSUE TITLE
Naming of the metrics

### ISSUE THREAD

**Issue by Zepp3** [Baukebrenninkmeijer/table-evaluator#23]
Hi,

I have a question about the naming of the output of the module. The single scores of the similarity score are called in the output:
Basic statistics                           
Correlation column correlations
Mean Correlation between fake and real columns 
Correlation RMSE                              
Similarity Score.

But in your thesis you write about:
Basic measures
Correlation matrix for mixed data types
Mirror column associations
Principle Component Analysis
Similarity score - machine learning efficacy.

I don't yet quite understand the connection between them.

**Comment by Baukebrenninkmeijer** [comment]
@Zepp3 That's indeed correct. That's mainly due to further evolvement of the metrics after my thesis, where I encountered either that some metrics weren't really that meaningful (such as the PCA one). I think the other names are just changed:
- `Correlation matrix for mixed data types` == `Correlation column correlations`
- `Mirror column associations` == `Mean Correlation between fake and real columns`

The ML efficacy is/should still be there afaik.

**Comment by Zepp3** [comment]
Ok, now it makes more sense to me.
The `Similarity score - machine learning efficacy` is not included as I can see, the score only gets calculated with `Basic statistics`, `Correlation column correlations`, `Mean Correlation between fake and real columns`, `Correlation RMSE`. So I guess PCA and `Similarity score - machine learning efficacy` are not part of the module anymore. But what is then the `Correlation RMSE`? Here is some example also:
![image](https://user-images.githubusercontent.com/36689688/148288632-54744835-d433-43d9-a5b8-b2a02ba2cfe6.png)

**Comment by Zepp3** [comment]
Or the `Similarity score - machine learning efficacy` is called `Correlation RMSE` in the module?

**Comment by Baukebrenninkmeijer** [comment]
@Zepp3 so, I split the ml efficacy into two different versions, since they require different metrics. If you're using regression, the metric is correlation rmse, or in other words how similar the rmse is. If you're using classification, you'll get percentage difference between F1 scores if I recall correctly. At least some measure over the F1 scores. 

Both should be considered ml efficacy but I gave them more descriptive names.

**Comment by Zepp3** [comment]
Thanks @Baukebrenninkmeijer, now it's completely clear to me!

**Comment by Baukebrenninkmeijer** [comment]
@Zepp3 Great! Yeah, I should probably document this somewhere sometime :|
